<article>
	<h1>
		Vice Squad gig announced
		<time>17th August 2017</time>
	</h1>
	<div class="grid">

		<div class="col-4-12">
			<img src="/assets/vice-squad.jpg">
		</div>
		<div class="col-8-12">
			<p>Bogans have Just been announced as support for DIY legends Vice Squad. they will be playing on the 9th of september 2017  at McLeans in Deeside. Other support will come from fellow Wrexham band 77 rejects.</p>
			<p>Tickets cost £9 advance - £12 on the door, so book 'em early.</p>
			<p>Doors 8 til late.</p>
		</div>
	</div>
</article>
