<article>
	<h1>
		Sex Pistols Experience gig announced
		<time>17th August 2017</time>
	</h1>
	<div class="grid">

		<div class="col-4-12">
			<img src="/assets/sex-pistols-experience.jpg">
		</div>
		<div class="col-8-12">
			<p>Bogans will be supporting the excellent Sex Pistols Experience on Friday 20th October 2017 at the Tivoli in Buckley.</p>
			<p>Tickets are a tenner. Winner, Winner, chicken dinner.</p>
		</div>
	</div>
</article>
