
    <article>
        <h1>
            Good things happen in 3's'
            <time>22nd August 2017</time>
        </h1>
        <div class="grid">

            <div class="col-4-12">
                <img src="/assets/wonk-unit.jpg">
            </div>
            <div class="col-8-12">
                <p>
                    First we get a support gig with one of our favourite bands WONK UNIT, at The Live Rooms in Chester on 23rd November 2017 (we have tickets for sale £7). Proper chuffed about that one.
                </p>
                <p>Then we get an awesome review from Sounds of the Streets. A right belter.</p>
                <p>Then we get featured in Musically Fresh's 15 Modern Punk Anthems. Honoured by that one.</p>
                <p>With all this attention in one day, we are really very flattered. Lets hope things stay this awesome.</p>
            </div>

        </div>

    </article>

