<header>


  <div class="hero-image">
      <img class="hero-image-header" src="assets/trans-bogans.png">
  <div class="image-collage">
      <div class="image"
        style="background-image: url('/assets/finland.jpg')">
      </div>
      <div class="image"
        style="background-image: url('assets/bogans-skull-logo.jpg')">
      </div>
      <div class="image"
        style="background-image: url('assets/more-finland.jpg')">
      </div>
      <div class="image"
        style="background-image: url('assets/wonk-unit.jpg')">
      </div>
  </div>
  </div>
  <nav>
    <a href="/#">
      <img class="nav-logo" src="assets/bogans-skull-logo.jpg">
    </a>
    <a href="/#">Home</a>
    <a href="news">News</a>
    <a href="reviews">Reviews</a>
  </nav>
</header>
