<header>
    <div class="hero-image">
        <img class="hero-image-header" src="assets/trans-bogans.png">
        <div class="image-collage">
            <div class="image"
                 style="background-image: url('assets/finland.jpg')">
            </div>
            <div class="image"
                 style="background-image: url('assets/bogans-skull-logo.jpg')">
            </div>
            <div class="image"
                 style="background-image: url('assets/more-finland.jpg')">
            </div>
        </div>
    </div>
    <nav>
        <div class="nav-container grid">
            <img class="nav-logo" src="assets/bogans-skull-logo.jpg">
            <a href="/#">Home</a>
            <a href="news">News</a>
            <a href="contact">Contact</a>
            <a href="reviews">Reviews</a>
        </div>
    </nav>
</header>
