<section id="contact">
    <h1>Contact Us</h1>
    Make an enquiry and we'll get back to you ASAP
    <form method="post">

        <div class="col-6-12">
            <div class="group">
                <label>Name</label>
                <input name="name" type="text">
            </div>
        </div>

        <div class="col-6-12">
            <div class="group">
                <label>Email</label>
                <input name="email" type="email" required>
            </div>
        </div>

        <div class="col-1-1">
            <div class="group">
                <label>Text</label>
                <textarea name="text" required></textarea>
            </div>
        </div>

        <div class="col-1-1">
            <div class="group">
                <input type="submit">
            </div>
        </div>

    </form>
</section>
