<section>
    <div class="review-home">
        &ldquo;{{ review.title }}&rdquo;
    </div>
            <div class="review-source"> <a href="{{ review.url }}">{{ review.source }}</a></div>
</section>

<section class="player">
    <div style="max-width: 500px; margin:auto;">
      <div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 100%;">
        <i id="loading-spinner" class="fa fa-spinner fa-spin fa-3x fa-fw"></i>
        <iframe
            src="https://bandcamp.com/EmbeddedPlayer/album=336918654/size=large/bgcol=ffffff/linkcol=0687f5/minimal=false/transparent=true/"
            style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute;"
            allowfullscreen
            scrolling="no">
        </iframe>
      </div>
    </div>

    <section class="gigs">
        <h1>Upcoming Shows</h1>

        {% for gig in gigs %}

            <div class="gig">
              <div class="grid">
                <div class="col-4-12">
                    <div class="gig-date-and-venue">
                        <time>{{ gig.date | date('l dS F Y') }}</time>
                    </div>
                </div>

                <div class="col-4-12">
                    <span>
                        {{ gig.prefix }}
                        <a href="{{ gig.url }}">{{ gig.artist}}</a>
                    </span>
                </div>

                <div class="col-4-12">
                    <div class="gig-location-details">
                        <span>{{ gig.location }}</span>
                    </div>
                </div>
              </div>
            </div>
        {% endfor %}

    </section>

    <section class="gigs">
        <h1>Past Shows</h1>

        {% for gig in pastGigs %}

            <div class="gig">
              <div class="grid">
                <div class="col-4-12">
                    <div class="gig-date-and-venue">
                        <time>{{ gig.date | date('l dS F Y') }}</time>
                    </div>
                </div>

                <div class="col-4-12">
                    <span>
                        {{ gig.prefix }}
                        <a href="{{ gig.url }}">{{ gig.artist}}</a>
                    </span>
                </div>

                <div class="col-4-12">
                    <div class="gig-location-details">
                        <span>{{ gig.location }}</span>
                    </div>
                </div>
              </div>
            </div>
        {% endfor %}

    </section>
