<section>
    <h2 class="card">Listen to Bogans on <a href="https://open.spotify.com/artist/6fupj4cJhQcvzGBmCcVErH">Spotify</a>!</h2>

    {% if review is not empty %}
    <div class="review-home">
        &ldquo;{{ review.title }}&rdquo;
    </div>
            <div class="review-source"> <a href="{{ review.url }}">{{ review.source }}</a></div>
    {% endif %}
</section>

<section class="player">
    <div style="max-width: 500px; margin:auto;">
      <div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 100%;">
        <i id="loading-spinner" class="fa fa-spinner fa-spin fa-3x fa-fw"></i>

        <iframe 
            style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute;"
            src="https://bandcamp.com/EmbeddedPlayer/album=3087519984/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/" seamless
            allowfullscreen
            scrolling="no">
            <a href="http://bogans.bandcamp.com/album/here-be-monsters">Here Be Monsters by Bogans</a>
        </iframe>

      </div>
    </div>
</section>

<section>
    <h1>News</h1>

    {% for article in articles | slice (0,3) %}
        <article>
            <h1>
                {{ article.title }}
                <a href="/news#{{ article.title }}" class="subtext">Read More</a>
            </h1>
        </article>
    {% endfor %}

</section>
    <section class="gigs">
        <h1>Upcoming Shows</h1>

        {% for gig in gigs %}

            <div class="card">
              <div class="grid">
                <div class="col-4-12">
                    <div class="gig-date-and-venue">
                        <time>{{ gig.date | date('l dS F Y') }}</time>
                    </div>
                </div>

                <div class="col-4-12">
                    <span>
                        {{ gig.prefix }}
                        <a href="{{ gig.url }}">{{ gig.artist}}</a>
                    </span>
                </div>

                <div class="col-4-12">
                    <div class="gig-location-details">
                        <span>{{ gig.location }}</span>
                    </div>
                </div>
              </div>
            </div>
        {% endfor %}

    </section>

    <section class="gigs">
        <h1>Past Shows <a class="subtext" href="/gigs">See all past gigs</a></h1>

        {% for gig in pastGigs | slice(0, 3) %}

            <div class="card">
              <div class="grid">
                <div class="col-4-12">
                    <div class="gig-date-and-venue">
                        <time>{{ gig.date | date('l dS F Y') }}</time>
                    </div>
                </div>

                <div class="col-4-12">
                    <span>
                        {{ gig.prefix }}
                        <a href="{{ gig.url }}">{{ gig.artist}}</a>
                    </span>
                </div>

                <div class="col-4-12">
                    <div class="gig-location-details">
                        <span>{{ gig.location }}</span>
                    </div>
                </div>
              </div>
            </div>
        {% endfor %}

    </section>
