<section>
    <h1>News</h1>
    <article>
        <h1>Good things happen in 3's'</h1>
        <time>22nd August 2017</time>
        <p>
            First we get a support gig with one of our favourite bands WONK UNIT, at The Live Rooms in Chester on 23rd November 2017 (we have tickets for sale £7). Proper chuffed about that one.
        </p>
        <p>Then we get an awesome review from Sounds of the Streets. A right belter.</p>
        <p>Then we get featured in Musically Fresh's 15 Modern Punk Anthems. Honoured by that one.</p>
        <p>With all this attention in one day, we are really very flattered. Lets hope things stay this awesome.</p>

    </article>
</section>
