<section>
    <h1>News</h1>

    {% for article in articles %}
        <article>
            <a name="{{ article.title }}"></a>
            <h1>
                {{ article.title }}
                <time class="subtext">{{ article.date | date('l dS F Y') }}</time>
            </h1>
            <div class="grid">
                <div class="col-4-12">
                    <img src="/assets/{{ article.image }}">
                </div>
                <div class="col-8-12">
                    <p>{{ article.text | nl2br }}</p>
                </div>
            </div>
        </article>
    {% endfor %}

</section>
