version: '2'

services:
  php:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/bogans
    ports:
      - "5678:80"
  mysql:
    build:
      context: ./docker/mysql/
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: symfony


