version: '2'

services:
  php:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/bogans
    ports: 
      - "5678:80"
    restart: always
  mysql:
    build:
      context: ./docker/mysql/
      dockerfile: Dockerfile
    restart: always


